### ISSUE TITLE
select/copy text from UI

### ISSUE THREAD

**Issue by dakaufma** [andres-erbsen/chatterbox#17]

**Comment by andres-erbsen** [comment]
Currently, each message and username is a separate text element in the UI. Making selection work inside each one is probably just a matter of passing the correct flag to QML. Making selection work across text elements would require being able to safely merge text from contacts into a single text area (for example, a "\n<b>andres</b> hi" in a message should not look the same as the user andres saying hi).

**Comment by dakaufma** [comment]
Do other chat UIs solve this problem? ...just tested and it looks like pidgin doesn't. Do other chat UIs solve the problem of making those messages look different?

One thought is that you could have two text elements one that has the name/message in it and one to the left with a bullet point or something before each new message --> distinguishes the two. But you'd also have to make sure scrolling is fixed between the two.

Another thought is maybe text elements can be extended to add an overlay?

Or maybe you can disallow some types of formatting in messages and use that formatting on names (i.e. if you were to disallow bold in messages this wouldn't be a problem, but you probably want to allow bold)

**Comment by andres-erbsen** [comment]
Fixed in 0d0523b868aff976c0383f295b107e8bd8d0d176: we use Go html escaper
