### ISSUE TITLE
settings menu

### ISSUE THREAD

**Issue by dakaufma** [andres-erbsen/chatterbox#22]
some way to edit all your protoc conf files from chatterbox-qt

**Comment by andres-erbsen** [comment]
We really don't want the average users to have to change *any* settings. Hopefully, all the things we will have knobs for will be obscure enough that anybody who wants to tweak them will also be comfortable using the protoc command line tools (maybe with my `pbe`). I think we should first try to make `pbe` more usable (by fixing https://github.com/andres-erbsen/pbe/issues/1 and https://github.com/andres-erbsen/pbe/issues/2), and then reevaluate the situation.
